# Generated by Django 4.2.2 on 2023-06-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2, verbose_name='Level'),
        ),
    ]
