# Generated by Django 4.2.2 on 2023-06-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0002_skill_status_alter_language_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('Na', 'Native'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
