# Generated by Django 4.2.2 on 2023-06-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0003_alter_language_level_alter_skill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='name',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
