# Generated by Django 4.2.2 on 2023-06-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0006_alter_skill_options_skill_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('Native', 'Native'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=6, verbose_name='Level'),
        ),
    ]
