# Generated by Django 4.2.2 on 2023-06-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0008_alter_experience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='position_name',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
