# Generated by Django 4.2.2 on 2023-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0009_experience_position_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('Bachelor Degree', 'Bachelor degree'), ('Engineering Degree', 'Engineer degree'), ('Master Degree', 'Master degree')], max_length=18, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
